/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recorridos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author aland
 */
public class Frame extends javax.swing.JFrame {
    
    int verNum = 0;
    ListaEnlazada list = new ListaEnlazada();
    int adyMat[][] = new int[25][25];

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        generatePane = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        aPosField = new javax.swing.JTextField();
        bPosField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        matText = new javax.swing.JTextArea();
        showButton = new javax.swing.JButton();
        startField = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        backPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        drawPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos GUI");
        setPreferredSize(new java.awt.Dimension(520, 530));
        setResizable(false);

        insertButton.setText("Insertar Arista");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\n<p> a: </p>\n<p> </p>\n<p> b: </p>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        matButton.setText("matriz de adyacencia");
        matButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matButtonActionPerformed(evt);
            }
        });

        matText.setColumns(20);
        matText.setRows(5);
        jScrollPane1.setViewportView(matText);

        showButton.setText("Ver Recorridos");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generatePaneLayout = new javax.swing.GroupLayout(generatePane);
        generatePane.setLayout(generatePaneLayout);
        generatePaneLayout.setHorizontalGroup(
            generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(generatePaneLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aPosField)
                            .addComponent(bPosField)))
                    .addComponent(insertButton))
                .addGap(31, 31, 31)
                .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        generatePaneLayout.setVerticalGroup(
            generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatePaneLayout.createSequentialGroup()
                .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generatePaneLayout.createSequentialGroup()
                        .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generatePaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(generatePaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(aPosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bPosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton)
                            .addComponent(matButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatePaneLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Generar Matriz de adyacencia", generatePane);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.SOUTH);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jLayeredPane1.setToolTipText("haz click donde quieras colocar un vertice");

        backPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPaneMouseClicked(evt);
            }
        });
        backPane.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recorridos/grid.png"))); // NOI18N
        backPane.add(jLabel1, java.awt.BorderLayout.CENTER);

        drawPane.setOpaque(false);

        javax.swing.GroupLayout drawPaneLayout = new javax.swing.GroupLayout(drawPane);
        drawPane.setLayout(drawPaneLayout);
        drawPaneLayout.setHorizontalGroup(
            drawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPaneLayout.setVerticalGroup(
            drawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(backPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(drawPane, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        int a = 0;
        int b = 0;
        boolean valid = true;
        try {
            a = Integer.parseInt(aPosField.getText());
            b = Integer.parseInt(bPosField.getText());
        } catch (NumberFormatException numberFormatException) {
            valid = false;
        }
        if (list.contains(a) && list.contains(b) && valid) {
            Graphics g = drawPane.getGraphics();
            Graphics2D g2 = (Graphics2D) g;
            g2.setStroke(new BasicStroke(2));
            int xposa = list.get(a).posX + 5;
            int yposa = list.get(a).posY;
            int xposb = list.get(b).posX + 5;
            int yposb = list.get(b).posY;
            g2.setColor(Color.blue);
            g2.drawLine(xposa, yposa, xposb, yposb);
            adyMat[a][b] = 1;
            adyMat[b][a] = 1;
        } else {
            matText.setText("Error");
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void backPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPaneMouseClicked
        Graphics g = drawPane.getGraphics();
        g.setColor(Color.RED);
        g.drawString(String.valueOf(verNum), evt.getX() - 6, evt.getY() + 4);
        g.drawOval(evt.getX() - 10, evt.getY() - 10, 20, 20);
        list.add(new nodo(verNum, evt.getX() - 10, evt.getY() - 10));
        verNum = verNum + 1;

    }//GEN-LAST:event_backPaneMouseClicked

    private void matButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matButtonActionPerformed
        matText.setText("");
        for (int i = 0; i < verNum; i++) {
            for (int j = 0; j < verNum; j++) {
                matText.setText(matText.getText() + adyMat[i][j] + " ");
            }
            matText.setText(matText.getText() + "\n");
        }
    }//GEN-LAST:event_matButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        int startVer = 0;
        boolean valid = true;
        try {
            startVer = Integer.parseInt(startField.getText());
        } catch (NumberFormatException numberFormatException) {
            valid = false;
        }
        
        if (verNum != 0 && list.contains(startVer) && valid) {
            Metodos met = new Metodos(verNum);
            StringBuffer paths = new StringBuffer();
            paths.append("BFS: \n");
            met.BFS(startVer, adyMat, paths);
            matText.setText(paths.toString());
            paths.append("\nDFS: \n");
            met.DFS(startVer, adyMat, paths);
            matText.setText(paths.toString());
        } else {
            matText.setText("Error");
        }
    }//GEN-LAST:event_showButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aPosField;
    private javax.swing.JTextField bPosField;
    private javax.swing.JPanel backPane;
    private javax.swing.JPanel drawPane;
    private javax.swing.JPanel generatePane;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton matButton;
    private javax.swing.JTextArea matText;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField startField;
    // End of variables declaration//GEN-END:variables
}
