
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adcerro
 */
public class MyFrame extends javax.swing.JFrame {

    private ABin tree = new ABin();
    private int xCoor;
    private int yCoor;
    private NodoB previous;

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
    }

    public void drawTree(NodoB nodo, int x, int y, Graphics g, int space) {
        //https://coderanch.com/t/558985/java/Draw-binary-tree-structure
        g.drawOval(x - 10, y - 10, 2 * 10, 2 * 10);
        if (nodo != null) {
            g.setColor(Color.black);
            g.drawString(nodo.dato + "", x - 6, y + 4);
        }
        if (nodo.Hizq != null) {
            g.setColor(Color.blue);
            hIzq(g, x - space, y + space, x, y, space);
            g.setColor(Color.BLACK);
            drawTree(nodo.Hizq, x - space, y + space, g, space / 2);
        }
        if (nodo.Hder != null) {
            g.setColor(Color.blue);
            hDer(g, x + space, y + space, x, y, space);
            g.setColor(Color.BLACK);
            drawTree(nodo.Hder, x + space, y + space, g, space / 2);
        }
    }

    private void hIzq(Graphics g, int x1, int y1, int x2, int y2, int space) {
        double d = Math.sqrt(space * space + (x2 - x1) * (x2 - x1));
        int x11 = (int) (x1 + 10 * (x2 - x1) / d);
        int y11 = (int) (y1 - 10 * space / d);
        int x21 = (int) (x2 - 10 * (x2 - x1) / d);
        int y21 = (int) (y2 + 10 * space / d);
        g.drawLine(x11, y11, x21, y21);
    }

    private void hDer(Graphics g, int x1, int y1, int x2, int y2, int space) {
        double d = Math.sqrt(space * space + (x2 - x1) * (x2 - x1));
        int x11 = (int) (x1 - 10 * (x1 - x2) / d);
        int y11 = (int) (y1 - 10 * space / d);
        int x21 = (int) (x2 + 10 * (x1 - x2) / d);
        int y21 = (int) (y2 + 10 * space / d);
        g.drawLine(x11, y11, x21, y21);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        nodeField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        insertButton.setText("Insertar Elemento");
        insertButton.setFocusable(false);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        nodeField.setToolTipText("Type a number here");
        nodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(insertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed

        String data = nodeField.getText();
        int valid = 1;
        int dataInt = 0;
        try {
            dataInt = Integer.parseInt(data);
        } catch (Exception e) {
            statusLabel.setText("Dato no aceptado");
            valid = 0;
        }
        if (valid != 0) {
            statusLabel.setText("Añadido");
            tree.insertaNodo(dataInt);
            drawTree(tree.Raiz, 280, 20, panel.getGraphics(), 140);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void nodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField nodeField;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
